version: '2'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ~/develop/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_NAME: amnesty
      WORDPRESS_TABLE_PREFIX: wp_
    working_dir: /var/www/html
    volumes:
      - ~/develop/amnesty/wp-content:/var/www/html/wp-content
